# Site settings
title:       Karine Arzoine Thoughts
email:       karine@arzoine.me 
author:      Karine Arzoine
description: "Hello there! I’m a financial mathematics student and I welcome you on my blog. Feel free to contact me if you have any questions concerning my prospective career,my blog or my tutoring services. I've recently learned that I was affected with the celiac disease. It has been a life changing discovery, and I would like to share some of my experiences with you."
baseurl:     "/thoughts"
url:         "http://karine.arzoine.me/thoughts/"

# Google analytics
google_analytics: UA-64155403-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: karinearzoineblog

# Social icons
show_social_icons: true
github_username:
twitter_username:
linkedin_username:

#Subscribe options
show_subscribe_option: true
subscribe_text: 'Subscribe to get more content like this one:'
email_value: 'your email address'

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true